spring:
  datasource:
    url: ${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USER}
    password: ${PRODUCT_DB_PASSWD}
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081